### ISSUE TITLE
Support for Extra CPUs

### ISSUE THREAD

**Issue by RuiXuqi** [PrototypeTrousers/Applied-Energistics-2#214] opened 2023-02-03 05:13 UTC
The Crafting Storage blocks of Extra CPUs will only work if at least one Crafting Storage block of the original mod Applied Energistics 2 is in the same multiblock, otherwise they are just not being recognized by the ME system. Maybe you can add support and solve this limitation.
Thank you!

**Comment by WaitingIdly** [comment] 2023-02-03 06:11
this is a duplicate of #57

**Closed** 2023-02-03 06:15 UTC
